name: .NET 6.0 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet packages
      run: dotnet restore Shapes.sln

    - name: Build the solution (Release)
      run: dotnet build Shapes.sln --configuration Release

    - name: Build the solution (Debug)
      run: dotnet build Shapes.sln --configuration Debug

    - name: Run tests (Release)
      run: dotnet test ShapeCharacteristicTests/ShapeCharacteristicTests.csproj --configuration Release --logger trx

    - name: Run tests (Debug)
      run: dotnet test ShapeCharacteristicTests/ShapeCharacteristicTests.csproj --configuration Debug --logger trx
